version: '3'
services:
  web:
    environment:
      - IS_DEV=False
    build: .
    ports:
      - "80:5000"
  db:
    image: "mongo:latest"
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "27017:27017"

